name: test_xignature_p_d_f
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  file_picker: ^5.3.0
  # syncfusion_flutter_pdfviewer: ^21.2.4
  flutter_pdfview: ^1.3.0
  image_picker: ^0.8.5+3
  syncfusion_flutter_pdf: ^21.2.4
  path_provider: ^2.0.15
  permission_handler: ^10.2.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

